---
deployment:
  tasks:
    - export APPROOT=/home/pinnacleinjury/rh-diary
    - /usr/local/bin/npm ci --prefix "$APPROOT" --omit=dev
    # - /usr/local/bin/npm run --prefix "$APPROOT" build   # if you have one
    - /bin/mkdir -p "$APPROOT/tmp"
    - /bin/touch "$APPROOT/tmp/restart.txt"               # restart Passenger
