name: Deploy to cPanel on push

on:
  push:
    branches: [ master ]        # change to main if needed
  workflow_dispatch:            # lets you trigger manually

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger cPanel UAPI Deployment
        run: |
          set -e
          echo "Calling cPanel UAPI for repository_root=${CPANEL_REPO_PATH}"
          HTTP_CODE=$(curl -sS -G -w "%{http_code}" -o response.json \
            -H "Authorization: cpanel ${CPANEL_USER}:${CPANEL_TOKEN}" \
            --data-urlencode "repository_root=${CPANEL_REPO_PATH}" \
            "https://${CPANEL_HOST}:2083/execute/VersionControlDeployment/create")
          echo "HTTP ${HTTP_CODE}"
          cat response.json
          jq -e '.status == 1' response.json >/dev/null
        env:
          CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
          CPANEL_USER: ${{ secrets.CPANEL_USER }}
          CPANEL_TOKEN: ${{ secrets.CPANEL_TOKEN }}
          CPANEL_REPO_PATH: ${{ secrets.CPANEL_REPO_PATH }}
